include colors.conf
font_family      Fira Code
font_size        10.0
enable_ligatures  yes
window_padding   10
tab_bar_position top
scrolling_factor 3.0
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
shell            /usr/bin/zsh
allow_remote_control yes
natural_scrolling yes
