# Set font family and size
font_family      Fira Code
font_size        10.0

# Set colors
foreground       #f7e9ee
background       #451916

# Enable ligatures
enable_ligatures  yes

# Set window and tab options
window_padding   10
tab_bar_position top

# Adjust scrolling behavior
scrolling_factor 3.0

# Set keybindings
map ctrl+shift+c copy
map ctrl+shift+v paste_from_clipboard

# Define custom commands
shell            /usr/bin/zsh

# Terminal behavior
allow_remote_control yes

# Enable natural text scrolling
natural_scrolling yes
